version: '3.9'

services:
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:main
    hostname: linkwarden
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/linkwarden/data:/data/data:rw
    environment:
      - DATABASE_URL=postgres://linkwardenuser:linkwardenpass@linkwarden-db:5432/linkwarden
      - NEXTAUTH_SECRET=v6M37byB5LwYHCPZyCJzDGNUSsHY4grj
      - NEXTAUTH_URL=http://localhost:3000
      # Additional Optional Settings
      # PAGINATION_TAKE_COUNT: 
      # STORAGE_FOLDER: 
      # AUTOSCROLL_TIMEOUT: 
      - NEXT_PUBLIC_DISABLE_REGISTRATION=false #or true
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: linkwarden-db
    image: postgres
    environment:
      - POSTGRES_DB=linkwarden
      - POSTGRES_USER=linkwardenuser
      - POSTGRES_PASSWORD=linkwardenpass
    volumes:
      - /data/linkwarden/db:/var/lib/postgresql/data:rw
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "linkwarden", "-U", "linkwardenuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: on-failure:5